export enum TRANSACTION_ACTION_TYPES {
  ADD_TRANSACTION = 'ADD_TRANSACTION',
  UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',
  DELETE_TRANSACTION = 'DELETE_TRANSACTION',
  SET_TRANSACTIONS = 'SET_TRANSACTIONS'
}